apiVersion: app/v1
kind: Deployment
metadata:
  name: shark-deployment
  labels:
  app: custom
spec:
  replicas: 2
  selector:
    matchLables:
      app: custom
  template:
   metadata:
     labels:
       app: custom
   spec:
    containers:
    - name: shark
      image: snehamj96/24febdevsecops
      ports:
      - containerPort: 8080
